### ISSUE TITLE
[bug] Commands standardisation two answers should be correct

### ISSUE THREAD

**Issue by mheki** [ProPheT777/certificationy-data#20]
Commands standardisation says that command name should be ended with `Command` text. 
Although the ending `ConsoleCommand` is not required, `MyTestConsoleCommand` as a command name is absolutely valid and will work fine.
That's why both `MyTestCommand.php` and `MyTestConsoleCommand.php` should be valid answers.

https://github.com/ProPheT777/certificationy-data/blob/master/symfony2/yaml/standardization.yml#L8

**Comment by ProPheT777** [comment]
Yes indeed, may be the question is badly written. From stantardization POV a command filename without `Command` at the end is wrong but technically work as expected.

May be we should rewrite the question ?

**Comment by mheki** [comment]
:+1: @ProPheT777 , we should.
What do you think about that:
`Using Console inside a bundle, which filename should be used for a "MyTest" command?`

**Comment by ProPheT777** [comment]
To be honest i'm not fan with your question :D 

> Using Console inside a bundle, which filename should be used for a "MyTest" command?

- We don't care of where he put the file (out of scope of the question)
- I'm not a huge fan to ask question over an example (I think this confused the reader and if questions are based on example that show we are not really aware to explain it with literral sentence)

I prefer something like this : 

> Following the naming convention, which filename is correct for command console class file ?

Because at the correction time, by reading the question you are aware of what is deterministic about the answser. Here it's rules by the Symfony **naming convention** 

What do you think that ?

**Comment by mheki** [comment]
__Naming convention__ sounds good, but still `MyTestConsoleCommand` is valid in terms of `*Command` naming convention.
Maybe we should indicate that only one answer here is correct or we want the shortest version of valid name?

**Comment by ProPheT777** [comment]
Yes another way can be to change `MyTestConsoleCommand` with a real fucked name ? In order to have one clear right answer ?

**Comment by mheki** [comment]
:smile:

**Comment by ProPheT777** [comment]
What do you prefer :D ?

**Comment by mheki** [comment]
`MyTestConsoleCmd` might be something what we're looking for

**Comment by ProPheT777** [comment]
yep ! :+1:
